### ISSUE TITLE
androidx support issue

### ISSUE THREAD

**Issue by mohsen-dl** [aminography/PrimeDatePicker#8]
please upgrade your library for androidx

**Comment by aminography** [comment]
Thanks for your suggestion. Supporting `androidx` will be done in the near future.
However, you can handle it yourself by copying the `PrimeDatePickerBottomSheet.kt` and `fragment_date_picker_bottom_sheet.xml` in your project and replace `appcompat` imports with `androidx` alternatives. Then use this class instead of `PrimeDatePickerBottomSheet`.

**Comment by aminography** [comment]
Please upgrade the library version to [1.1.0](https://github.com/aminography/PrimeDatePicker#version-110)
